# Generated by Django 5.1.5 on 2025-04-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.bucket'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.income'),
        ),
    ]
