# Generated by Django 5.1.5 on 2025-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('RENT/MORTGAGE', 'Rent/Mortgage'), ('UTILITIES', 'Utilities'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas'), ('INTERNET', 'Internet'), ('HOME MAINTENANCE', 'Home Maintenance'), ('HOME INSURANCE', 'Home Insurance'), ('PROPERTY TAXES', 'Property Taxes'), ('OTHER HOUSING EXPENSES', 'Other Housing Expenses'), ('TRANSPORTATION', 'Transportation'), ('CAR PAYMENT', 'Car Payment'), ('GAS/FUEL', 'Gas/Fuel'), ('PUBLIC TRANSIT', 'Public Transit'), ('RIDE SHARING', 'Ride Sharing'), ('CAR INSURANCE', 'Car Insurance'), ('CAR MAINTENANCE', 'Car Maintenance'), ('PARKING/TOLLS', 'Parking/Tolls'), ('OTHER TRANSPORTATION EXPENSES', 'Other Transportation Expenses'), ('FOOD', 'Food'), ('GROCERIES', 'Groceries'), ('DINING OUT', 'Dining Out'), ('COFFEE SHOPS', 'Coffee Shops'), ('ALCOHOL/BARS', 'Alcohol/Bars'), ('OTHER FOOD EXPENSES', 'Other Food Expenses'), ('HEALTH', 'Health'), ('HEALTH INSURANCE', 'Health Insurance'), ('DOCTOR VISITS', 'Doctor Visits'), ('MEDICATIONS', 'Medications'), ('GYM MEMBERSHIP', 'Gym Membership'), ('WELLNESS/SUPPLEMENTS', 'Wellness/Supplements'), ('OTHER HEALTH EXPENSES', 'Other Health Expenses'), ('ENTERTAINMENT', 'Entertainment'), ('STREAMING SERVICES', 'Streaming Services'), ('MOVIES/THEATER', 'Movies/Theater'), ('CONCERTS/EVENTS', 'Concerts/Events'), ('HOBBIES', 'Hobbies'), ('GAMES', 'Games'), ('SUBSCRIPTIONS', 'Subscriptions'), ('OTHER ENTERTAINMENT EXPENSES', 'Other Entertainment Expenses'), ('SHOPPING', 'Shopping'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('HOME GOODS', 'Home Goods'), ('BEAUTY/PERSONAL CARE', 'Beauty/Personal Care'), ('GIFTS', 'Gifts'), ('OTHER SHOPPING EXPENSES', 'Other Shopping Expenses'), ('TRAVEL', 'Travel'), ('FLIGHTS', 'Flights'), ('ACCOMMODATION', 'Accommodation'), ('TRANSPORTATION', 'Transportation'), ('FOOD/DRINK', 'Food/Drink'), ('ACTIVITIES', 'Activities'), ('TRAVEL INSURANCE', 'Travel Insurance'), ('OTHER TRAVEL EXPENSES', 'Other Travel Expenses'), ('DEBT PAYMENTS', 'Debt Payments'), ('CREDIT CARD PAYMENTS', 'Credit Card Payments'), ('STUDENT LOANS', 'Student Loans'), ('PERSONAL LOANS', 'Personal Loans'), ('OTHER DEBT PAYMENTS', 'Other Debt Payments'), ('SAVINGS', 'Savings'), ('EMERGENCY FUND', 'Emergency Fund'), ('RETIREMENT SAVINGS', 'Retirement Savings'), ('INVESTMENT CONTRIBUTIONS', 'Investment Contributions'), ('OTHER SAVINGS', 'Other Savings'), ('EDUCATION', 'Education'), ('TUITION', 'Tuition'), ('BOOKS/SUPPLIES', 'Books/Supplies'), ('COURSES/WORKSHOPS', 'Courses/Workshops'), ('OTHER EDUCATION EXPENSES', 'Other Education Expenses'), ('CHILDCARE', 'Childcare'), ('BABYSITTING', 'Babysitting'), ('SCHOOL FEES', 'School Fees'), ('CHILD ACTIVITIES', 'Child Activities'), ('OTHER CHILDCARE EXPENSES', 'Other Childcare Expenses'), ('PETS', 'Pets'), ('PET FOOD', 'Pet Food'), ('VETERINARY CARE', 'Veterinary Care'), ('PET SUPPLIES', 'Pet Supplies'), ('PET INSURANCE', 'Pet Insurance'), ('OTHER PET EXPENSES', 'Other Pet Expenses'), ('GIFTS/DONATIONS', 'Gifts/Donations'), ('CHARITABLE DONATIONS', 'Charitable Donations'), ('GIFTS FOR OTHERS', 'Gifts for Others'), ('OTHER GIFTS/DONATIONS', 'Other Gifts/Donations'), ('BUSINESS EXPENSES', 'Business Expenses'), ('OFFICE SUPPLIES', 'Office Supplies'), ('TRAVEL EXPENSES', 'Travel Expenses'), ('MARKETING/ADVERTISING', 'Marketing/Advertising'), ('OTHER BUSINESS EXPENSES', 'Other Business Expenses'), ('MISCELLANEOUS', 'Miscellaneous'), ('OTHER EXPENSES', 'Other Expenses')], max_length=30)),
                ('percentage_of_income', models.IntegerField(blank=True, null=True)),
                ('due_frequency', models.DurationField()),
                ('next_due', models.DateField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fulfilled', models.BooleanField()),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE INCOME', 'Freelance Income'), ('INVESTMENT INCOME', 'Investment Income'), ('RENTAL INCOME', 'Rental Income'), ('SIDE HUSTLE', 'Side Hustle'), ('GIFTS', 'Gifts'), ('REFUNDS/REIMBURSEMENTS', 'Refunds/Reimbursements'), ('OTHER INCOME', 'Other Income')], max_length=30)),
                ('pay_frequency', models.DurationField()),
                ('next_payday', models.DateField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
