# Generated by Django 5.1.5 on 2025-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('HOUSING', 'Housing'), ('RENT_MORTGAGE', 'Rent/Mortgage'), ('UTILITIES', 'Utilities'), ('HOME_MAINTENANCE', 'Home Maintenance'), ('HOME_INSURANCE_TAXES', 'Home Insurance/Taxes'), ('TRANSPORTATION', 'Transportation'), ('VEHICLE_PAYMENT', 'Vehicle Payment'), ('VEHICLE_EXPENSES', 'Vehicle Expenses'), ('PUBLIC_TRANSPORT', 'Public Transport'), ('PARKING_TOLLS', 'Parking/Tolls'), ('FOOD', 'Food'), ('GROCERIES', 'Groceries'), ('DINING_OUT', 'Dining Out'), ('HEALTHCARE', 'Healthcare'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MEDICAL_EXPENSES', 'Medical Expenses'), ('FITNESS', 'Fitness'), ('ENTERTAINMENT', 'Entertainment'), ('STREAMING_SUBSCRIPTIONS', 'Streaming/Subscriptions'), ('RECREATION', 'Recreation'), ('SHOPPING', 'Shopping'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('PERSONAL_CARE', 'Personal Care'), ('TRAVEL', 'Travel'), ('ACCOMMODATION', 'Accommodation'), ('TRAVEL_TRANSPORT', 'Travel Transport'), ('TRAVEL_ACTIVITIES', 'Travel Activities'), ('DEBT', 'Debt'), ('SAVINGS_INVESTMENTS', 'Savings/Investments'), ('EDUCATION', 'Education'), ('CHILDCARE', 'Childcare'), ('PETS', 'Pets'), ('GIFTS_DONATIONS', 'Gifts/Donations'), ('BUSINESS', 'Business Expenses'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=30),
        ),
    ]
