# Generated by Django 5.1.5 on 2025-03-28 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together={('user', 'expense', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='goals',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user', 'period')},
        ),
    ]
