# Generated by Django 5.1.5 on 2025-03-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_transaction_account_expense_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE INCOME', 'Freelance Income'), ('INVESTMENT INCOME', 'Investment Income'), ('RENTAL INCOME', 'Rental Income'), ('SIDE HUSTLE', 'Side Hustle'), ('GIFTS', 'Gifts'), ('REavailable_funds/REIMBURSEMENTS', 'Reavailable_funds/Reimbursements'), ('OTHER INCOME', 'Other Income')], max_length=32),
        ),
        migrations.AlterField(
            model_name='income',
            name='pay_frequency',
            field=models.DurationField(choices=[('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-weekly'), ('SEMI-MONTHLYMONTHLY', 'Semi-monthlyMonthly'), ('BI-MONTHLY', 'Bi-monthly'), ('ANNUALLY', 'Annually')]),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENT', 'Investment'), ('DEBT_REPAYMENT', 'Debt Repayment'), ('EMERGENCY_FUND', 'Emergency Fund'), ('RETIREMENT', 'Retirement'), ('EDUCATION', 'Education'), ('VACATION', 'Vacation'), ('HOME', 'Home'), ('CAR', 'Car'), ('OTHER', 'Other')], max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fulfilled', models.BooleanField()),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('available_funds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_goals', models.DecimalField(decimal_places=2, max_digits=20)),
                ('carry_forward', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'unique_together': {('period',)},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due', models.DateField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fullfilled', models.BooleanField()),
                ('expense', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='budget', to='budget.expense')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='budget.session')),
            ],
            options={
                'unique_together': {('expense', 'session')},
            },
        ),
    ]
