# Generated by Django 5.1.5 on 2025-04-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_bucket_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='amount',
            new_name='current_amount',
        ),
    ]
