# Generated by Django 5.1.5 on 2025-03-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_income_category_alter_income_pay_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due', models.DateField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fullfilled', models.BooleanField()),
                ('expense', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='expense', to='budget.expense')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='budget.session')),
            ],
            options={
                'unique_together': {('expense', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
