# Generated by Django 5.1.5 on 2025-03-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_session_total_funds_bucket_delete_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='fullfilled',
            new_name='fulfilled',
        ),
    ]
