# Generated by Django 5.1.5 on 2025-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_amount_bucket_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='goals',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
