# Generated by Django 5.1.5 on 2025-04-13 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_goals_target_date_alter_goals_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
