# Generated by Django 5.1.5 on 2025-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_expense_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
