# Generated by Django 5.1.5 on 2025-04-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_bucket_current_amount_alter_bucket_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='percentage_of_income',
        ),
        migrations.AlterField(
            model_name='expense',
            name='due_frequency',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='next_due',
            field=models.DateField(null=True),
        ),
    ]
