# Generated by Django 5.1.5 on 2025-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_remove_expense_current_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='due_frequency',
            new_name='payment_frequency',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
