# Generated by Django 5.1.5 on 2025-04-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_rename_due_frequency_expense_payment_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='next_due',
            new_name='next_payment',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='next_due',
            new_name='next_payment',
        ),
    ]
