# Generated by Django 5.1.5 on 2025-04-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_rename_next_due_bucket_next_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='target_amount',
            new_name='spending_limit',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='target_amount',
            new_name='spending_limit',
        ),
    ]
