# Generated by Django 5.1.5 on 2025-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_rename_target_amount_bucket_spending_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE INCOME', 'Freelance Income'), ('INVESTMENT INCOME', 'Investment Income'), ('RENTAL INCOME', 'Rental Income'), ('SIDE HUSTLE', 'Side Hustle'), ('GIFTS', 'Gifts'), ('REIMBURSEMENTS', 'Reimbursements'), ('OTHER INCOME', 'Other Income')], max_length=32),
        ),
        migrations.AlterField(
            model_name='income',
            name='pay_frequency',
            field=models.DurationField(choices=[('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-weekly'), ('SEMI-MONTHLY', 'Semi-monthly'), ('MONTHLY', 'Monthly'), ('BI-MONTHLY', 'Bi-monthly'), ('ANNUALLY', 'Annually')]),
        ),
    ]
