# Generated by Django 5.1.5 on 2025-04-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_income_category_alter_income_pay_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
