# Generated by Django 5.1.5 on 2025-04-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_bucket_next_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='carry_forward',
        ),
    ]
