# Generated by Django 5.1.5 on 2025-04-19 04:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_remove_session_carry_forward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together={('user', 'expense', 'session', 'next_payment')},
        ),
    ]
