# Generated by Django 5.1.5 on 2025-04-19 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_alter_bucket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
