# Generated by Django 5.1.5 on 2025-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_expense_active_goals_active_goals_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='active',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='active',
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
