# Generated by Django 5.1.5 on 2025-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_remove_expense_active_remove_goals_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='pay_frequency',
            field=models.DurationField(choices=[('ONE-TIME', 'One-time'), ('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-weekly'), ('SEMI-MONTHLY', 'Semi-monthly'), ('MONTHLY', 'Monthly'), ('BI-MONTHLY', 'Bi-monthly'), ('ANNUALLY', 'Annually')]),
        ),
    ]
