# Generated by Django 5.1.5 on 2025-04-27 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_alter_income_pay_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='pay_frequency',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), 'Daily'), (datetime.timedelta(days=7), 'Weekly'), (datetime.timedelta(days=14), 'Bi-weekly'), (datetime.timedelta(days=15), 'Semi-monthly'), (datetime.timedelta(days=30), 'Monthly'), (datetime.timedelta(days=60), 'Bi-monthly'), (datetime.timedelta(days=90), 'Quarterly'), (datetime.timedelta(days=180), 'Semi-annually'), (datetime.timedelta(days=365), 'Annually'), (datetime.timedelta(0), 'One-time'), (datetime.timedelta(days=3), 'Every 3 days'), (datetime.timedelta(days=10), 'Every 10 days'), (datetime.timedelta(days=21), 'Every 3 weeks'), (datetime.timedelta(days=28), 'Every 4 weeks')]),
        ),
    ]
