# Generated by Django 5.1.5 on 2025-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_alter_income_pay_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='pay_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('SEMIMONTHLY', 'Semi-monthly (1st and 15th)'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bi-monthly (Every 2 months)'), ('QUARTERLY', 'Quarterly'), ('SEMIANNUALLY', 'Semi-annually'), ('ANNUALLY', 'Annually'), ('ONETIME', 'One-time'), ('EVERY_3_DAYS', 'Every 3 days'), ('EVERY_10_DAYS', 'Every 10 days'), ('EVERY_3_WEEKS', 'Every 3 weeks'), ('EVERY_4_WEEKS', 'Every 4 weeks')], max_length=20),
        ),
    ]
